version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:9000"
    ports:
      - 8000:9000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecrectkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=ultimate_django
      - DB_USER=devuser
      - DB_PASS=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=ultimate_django
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme